from typing import overload

@overload
def x() -> None:...
@overload
def x(name: str) -> str:...
@overload
def x(name: str, last_name: str) -> str:...
@overload
def x(name: str, address: str) -> bool:...
