from typing import overload

@overload
def x(name: str) -> str:...
@overload
def x(name: str, last_name: str) -> str:...
@overload
def x(name: str, address: str) -> bool:...
def y(name: str) -> int:...
class Test:
    @staticmethod
    def speak(word: str) -> str:...